### ISSUE TITLE
Failed to generate clearance:views after clearance:routes

### ISSUE THREAD

**Issue by eleidan** [thoughtbot/clearance#539] opened 2015-03-09 20:00 UTC
### How to reproduce
1. Create new app:
  ```
  rails _4.2.0_ new <app_name>
  cd <app_name>
  ```
    
2. Install *Clearance*:
  ```
  rails g clearance:install
  ```
    
3. Generate routes:
  ```
  rails g clearance:routes
  ```

4. Generate views:
  ```
  rails g clearance:views
  ```

The last instruction should reveal the issue.
I got the following lines of output:

```
/home/<user_name>/.rvm/gems/ruby-2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:538:in `add_route': Invalid route name, already in use: 'sign_in' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created (ArgumentError)
```

As a result, the `rails g clearance:views` command provides no changes to the project.

**Comment by eleidan** [comment] 2015-03-09 20:16
Let me know if additional information is needed.

**Comment by derekprior** [comment] 2015-03-09 21:47
Can you show me your existing routes file from before you run step 4/

**Comment by eleidan** [comment] 2015-03-10 16:51
@derekprior actually, I desribed all the steps to get the same state, but here you are:
```ruby
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'
end
```

**Comment by eleidan** [comment] 2015-03-10 16:54
And here is the info about the gem I am using:
```
$ gem list clearance

*** LOCAL GEMS ***

clearance (1.8.1)
```

**Comment by derekprior** [comment] 2015-03-11 01:23
This isn't a problem with the view generator, it's a problem starting the app. The routes were generated locally but the Clearance configuration is not set to disable the internal routes. If you open `config/initializers/clearance.rb` and add `config.routes = false`, the view generator will work.

We should probably make this happen automatically somehow.

**Comment by eleidan** [comment] 2015-03-11 10:48
After adding `config.routes = false` to my `config/initializers/clearance.rb` I managed to generate views with `rails g clearance:views`.
I don't understand what you mean under 'The routes were generated locally', as I have a git repository and I can check if I have changes. So, the `rails g clearance:views` command failed with exception (error), and generated no views :smiley: 
What can I say about it. They say, if one does something according to the documentation and gets an error, then there are at least two reasons for that, as follows:
1. We have bad documentation.
2. We found a bug.

I see no problem in such a behavior of generators. I think this should be documented properly, maybe right in the README. But of course it's up to you, guys, to decide how to solve it better.
Stay cool!

**Comment by derekprior** [comment] 2015-03-11 14:16
> I don't understand what you mean under 'The routes were generated locally', as I have a git repository and I can check if I have changes.

I mean you ran the routes generator, which copied Clearance's routes to your `config/routes` file. However, it did not also set your config to disable Clearance's internal routes. So Rails refuses to start because of duplicate routes.

> They say, if one does something according to the documentation and gets an error, then there are at least two reasons for that, as follows:
> 1. We have bad documentation.
> 2. We found a bug.

The issue is still open because I intend to address it somehow - likely with a code fix and documentation both. I may not have time to address it for a bit, so if you'd like to take a crack at a fix, feel free.

**Comment by derekprior** [comment] 2015-08-21 18:45
@eleidan Thanks for bringing this to my attention. The issue has been fixed by updating the routes generator. This will likely be released later today.

**Closed** 2015-08-21 18:44 UTC
Labels: bugs
