### ISSUE TITLE
TypeError on sign_up page

### ISSUE THREAD

**Issue by sonalkr132** [thoughtbot/clearance#900] opened 2020-07-14 05:32 UTC
Following error gets raised if the user submits a request with URL: `/sign_up?user=JJJ12QQQ`:
```
 TypeError:
       no implicit conversion of Symbol into String
     # ./app/controllers/clearance/users_controller.rb:34:in `delete'
     # ./app/controllers/clearance/users_controller.rb:34:in `user_from_params'
     # ./app/controllers/clearance/users_controller.rb:6:in `new'
```
[Build reproducing error](https://travis-ci.org/github/sonalkr132/clearance/jobs/707872342#L474).

**Comment by eebs** [comment] 2020-07-24 17:43
Thanks for taking the time to open an issue. For the reasons mentioned on the [rubygems issue](https://github.com/rubygems/rubygems.org/pull/2456#issuecomment-663654032), this is expected behavior, so we are going to close this issue.

**Closed by eebs** 2020-07-24 17:43 UTC
