### ISSUE TITLE
Two separate user models in a single application

### ISSUE THREAD

**Issue by AlphaB** [thoughtbot/clearance#770] opened 2018-01-24 15:52 UTC
Hi! Is it possible to have 2 separate models with two separate login pages say `User` and `AdminUser` in a single application? I can't find a simple way to do that.
Thanks!

**Comment by oleg-kiviljov** [comment] 2018-03-13 23:59
Also interested in how to implement this. I have same use case as AlphaB.

**Comment by carlesjove** [comment] 2018-06-11 21:28
I tried this too and couldn't found a way that didn't imply duplicating and overriding a lot of code, so got to the conclusion that this is discouraged by design.

With Clearance as it is, I've found the best way is to simply use the same model and add an `admin?` method, be it with a `boolean` or with a more complex logic behind it. Then, simply create an `admin` namespace and its own set of routes within a Clearance constraint:

```
  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    get "/admin", to: "admin#index"
    namespace :admin do
      resources :posts
    end
  end
```

and finally group some login for all admin controllers in a concern:

```
module AdminPanel
  extend ActiveSupport::Concern

  included do
    layout "admin"
    before_action :require_login
  end

  private

  // This is the only method to override
  def require_login
    deny_access("Only admins here") unless signed_in? && current_user.admin?
  end
end

class Admin::Posts < ApplicationController
  include AdminPanel
end
```

Now only admins will be able to access `/admin` routes, while all others will get `500` errors, and also has the benefit that you'll be able to use the application as a regular user would, which I think is great after all.

So well, not really a solution to the specific issue but, again, I have the feeling that they've made this decision by design. Of course, I might be wrong :-)

**Comment by mjankowski** [comment] 2019-11-14 14:26
> I have the feeling that they've made this decision by design

I think this is more or less accurate.

I'm going to close this on the assumption that "use a boolean attribute or some other role system instead of different models" is the approach we'd take with clearance auth on an app with this requirement.

**Closed by mjankowski** 2019-11-14 14:26 UTC
