### ISSUE TITLE
1.16.2 broke Session store not setting cookie

### ISSUE THREAD

**Issue by dakotalightning** [thoughtbot/clearance#822] opened 2019-03-02 23:49 UTC
Either I'm missing a new setting somewhere, but I've tested 1.16.2 and 1.16.1. The latest version 1.16.1 breaks the session store. There is no user in the session, and I think this might have something to do with it.

https://github.com/thoughtbot/clearance/blob/v1.16.1/lib/clearance/session.rb#L57
https://github.com/thoughtbot/clearance/blob/master/lib/clearance/session.rb#L60

**Comment by mjankowski** [comment] 2019-03-03 13:44
Possibly related (or same issue) as https://github.com/thoughtbot/clearance/issues/821

Can you give sample code of what broke?

**Comment by coneybeare** [comment] 2019-03-04 23:03
I'm seeing this on 1.16.2 as well. Where standard login is not setting anything in the session, and thus we get

````
Filter chain halted as :require_login rendered or redirected
````

A downgrade to 1.16.1 immediately resolved the issue.

**Comment by mjankowski** [comment] 2019-03-04 23:08
Thanks. Does it appear to be setting the cookie but not setting in the session in the req that should have signed in?

**Comment by coneybeare** [comment] 2019-03-05 01:49
After upgrading to 1.6.2 and logging in, I can see a successful login and redirect to `url_after_create`, but a `render_login` failure. At this point, there is not a `remember_me_token` cookie in the store, only the session cookie. Doing the same thing on 1.6.1 creates the `remember_me_token` properly, which I assume is what is being used to log in the user on subsequent requests.

**Comment by dakotalightning** [comment] 2019-03-05 03:22
^ 

I've expreince the same thing, after the `status.success?` check during the `session::sign_in` the cookie isn't being set. I've checked `current_user` after the redirect, and it is `nil`. My assumption is that `before_action :require_login` fails even if `sign_in` is a success. 

https://github.com/thoughtbot/clearance/blob/master/lib/clearance/authentication.rb#L94

I hope that helps.

I'm using a basic config.

```ruby
Clearance.configure do |config|

  config.routes = false
  config.mailer_sender = 'noreply@site.com'
  config.redirect_url = '/dashboard'
  config.cookie_expiration = lambda { |cookies| 2.weeks.from_now.utc }
  config.secure_cookie = true
  config.rotate_csrf_on_sign_in = true

end
```

**Comment by mjankowski** [comment] 2019-03-05 14:26
I'm having trouble replicating this in local apps. I've got one app which just relies on the clearance controllers directly, and another that subclasses them. Both have test suites which exercise signing in and out, and the suites pass. I've also confirmed manually that I can sign in/out of the running apps locally while using 1.16.2.

My suspicions are that there's at least one and maybe two issues related to either:

- Changes made around interaction between custom domain settings and how we set cookies
- Changes made to fix a bug that set too many cookies which moved cookie setting into the middleware and out of the controller level

Can you confirm further:

- Does `rake middleware` include `Clearance::RackSession` ?
- Are you modifying the domain clearance sets cookies on (or otherwise doing anything interesting with domains in your app, I guess)
- Are you sub-classing clearance controllers, or just using straight up

Beyond that - getting either of a) minimal sample app to reproduce issue, b) clearance fork/branch which adds a failing spec - would be great.

I will continue to attempt to replicate locally.

**Comment by dakotalightning** [comment] 2019-03-08 18:30
I can confirm both `rake middleware` and I am not modifying the domain.

Here is my `SessionsController`.

```ruby
class SessionsController < Clearance::SessionsController

  layout "minimal"

  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        redirect_back_or url_after_create
      else
        flash.now.notice = status.failure_message
        render template: "sessions/new", status: :unauthorized
      end
    end
  end

private

  def url_after_destroy
    root_path
  end

  def url_after_create
    dashboard_root_path
  end

end
```

I can also confirm it fails on `ruby 2.5.3` and `rails 5.2.2`
Here are my clearance specs that fail if it helps.

```
rspec ./spec/features/clearance/user_signs_out_spec.rb:5 # User signs out sign in and out
rspec ./spec/features/clearance/visitor_signs_in_spec.rb:5 # Visitor signs in with valid email and password
rspec ./spec/features/clearance/visitor_signs_in_spec.rb:12 # Visitor signs in with valid mixed-case email and password 
rspec ./spec/features/clearance/visitor_signs_up_spec.rb:22 # Visitor signs up with valid email and password
rspec ./spec/features/clearance/visitor_updates_password_spec.rb:5 # Visitor updates password with valid password
rspec ./spec/features/clearance/visitor_updates_password_spec.rb:12 # Visitor updates password signs in with new password
```

**Comment by mjankowski** [comment] 2019-04-05 16:33
@coneybeare and @dakotalightning - are you setting the clearance `cookie_domain` setting?

If not, are you setting a domain name elsewhere in your specs?

**Comment by coneybeare** [comment] 2019-04-05 16:46
I am setting the `cookie_domain` in the initializer to `".mydomain.com"`

**Comment by dakotalightning** [comment] 2019-04-05 17:09
I am not setting it anywhere; my settings are above.
https://github.com/thoughtbot/clearance/issues/822#issuecomment-469521235

**Comment by mjankowski** [comment] 2019-04-05 17:35
Relevant to `cookie_domain` - I believe that in earlier versions we were setting two cookies, and one of them had the domain and one did not have the domain. A side effect of this was that in places where the app was being accessed in ways that were NOT over the specified cookie domain - it would still work, because the one cookie which was set without the domain would still come through and be set.

In 1.16.2 we fixed the duplicate cookie setting so now the only cookie being set is the one with the domain name - which means that places which were previously (probably unknowingly) relying on this behavior would have broken.

@coneybeare if you add a `host! '.mydomain.com'` to your suite (or whatever other means is necessary to tell rack/rails/capybara/etc to use that hostname), does that help?

**Comment by coneybeare** [comment] 2019-04-05 17:55
@mjankowski I'll have to check it out after an update, but you may be on to something. I test on a different domain using a self signed certificate. `Capybara.app_host` is being set to `https://localhost.test`.

If I am understanding correctly, and your idea is indeed the root cause, this could be solved by either removing my cookie_domain value and using default, or by setting it to `localhost.test` in the test environment, right?

**Comment by mjankowski** [comment] 2019-04-05 17:59
Yes, I think either removing the setting in the test env, or making sure the setting matches whatever the requests are being sent as in the test env - would probably solve.

**Comment by mjankowski** [comment] 2019-04-08 17:41
I'm going to close this on the assumption that the misc domain/cookie/test topics discussed here were the issue, and that this can be resolved via updating your env configs to match up.

If anyone is seeing this issue in a non-test environment or in a way that's not resolved by fixing the domain config, let us know.

**Closed by mjankowski** 2019-04-08 17:41 UTC

**Comment by dwightwatson** [comment] 2019-05-10 04:44
For reference, I don't have `cookie_domain` customised on my app, but I did have `secure_cookie` set to true. I assume it's the same issue under the hood but just another way to come across it.

My fix was similar to one of the solutions offered in the related tickets

```rb
config.secure_cookie = true if Rails.env.production?
```
