### ISSUE TITLE
Hotwire Turbo Support

### ISSUE THREAD

**Issue by kwhandy** [thoughtbot/clearance#946] opened 2021-09-01 22:07 UTC
Hi, is this gem support hotwire turbo(turbo-rails) which requires to replace ujs and turbolinks?

**Comment by MatheusRich** [comment] 2021-09-17 14:58
@aledustet can we close this as a duplicate of #929?

**Comment by MatheusRich** [comment] 2021-09-24 13:55
I'll close this in favor of #929.

**Closed by MatheusRich** 2021-09-24 13:55 UTC
