### ISSUE TITLE
Signed in user ends up logged in as another user after some period of time

### ISSUE THREAD

**Issue by rezart** [thoughtbot/clearance#781] opened 2018-03-12 17:45 UTC
I am running into an issue where some users are reporting that after awhile of using the site they show up logged in as another user. I have checked to make sure that it is not a cacheing issue without much luck. I am not personally able to reproduce but can see the user's logged in as someone else based on the logs. I am wondering if Cloudflare's cacheing is returning someone else's cookie in the response header. Has anyone else run into this issue?

**Comment by rezart** [comment] 2018-03-12 20:09
Thinking it could be related to #753
cc @rogercampos were you able to make progress on it?

**Comment by rogercampos** [comment] 2018-03-13 11:53
@rezart what you're describing seems to directly correlate to the issue fixed there. Check if you're using public http caching in **any** of your app endpoints, and perform tests issuing requests as an authenticated used. If you receive from your app any response with "cache-control" public and "set-cookie", that's bad.

**Comment by rezart** [comment] 2018-05-24 22:07
This issue is still persisting for a number of my users (ie. they are logged in as themselves and after some time they notice to be logged in as someone else). I have disabled cacheing completely from Cloudflare and have confirmed that all my server responses are returning 'cache-control: no-cache' or 'cache-control: max-age=0, private, must-revalidate'. Is there something else I may be missing?

**Comment by gbirchmeier** [comment] 2019-11-07 17:01
The age of this obviously-critical issue has convinced me that Clearance is not an able replacement for Devise (which I hate).  How is this issue not at the top of the priority list?  There's a year-old PR that supposedly addresses this!

**Comment by mjankowski** [comment] 2019-11-07 17:35
Thanks for the nudge and relaying your concern.

If we can get steps to replicate/reproduce this, we can triage/prioritize. It's hard to proceed without that.

**Comment by rogercampos** [comment] 2019-11-08 09:04
@mjankowski you have a spec that shows the issue here:

https://github.com/thoughtbot/clearance/pull/753/files#diff-dedb3fde3cfe0b0a03b101a83ef4f77d

as well as a possible implementation fix.

**Comment by mjankowski** [comment] 2019-11-08 16:17
Sorry, it wasn't clear to me (and still isn't really) from the discussion history here that "signed in users suddenly become other signed users" had been reproduced and root cause found.

It strikes me as plausible/believable that they are the same issue ... I just missed the direct link in my first pass reading here. I will review the linked PR soon!

**Comment by mjankowski** [comment] 2019-11-14 16:42
I'm going to close this on the assumption that https://github.com/thoughtbot/clearance/pull/869 (which includes all of https://github.com/thoughtbot/clearance/pull/753) resolves this.

It would still be great to get a narrower reproducible series of steps here to see this behavior if anyone can do that.

**Closed by mjankowski** 2019-11-14 16:42 UTC

**Comment by gbirchmeier** [comment] 2019-12-05 16:36
Thanks for moving on this.  I'll keep an eye on this gem, maybe I can use it in a future project.

**Comment by rezart** [comment] 2021-05-06 17:54
FWIW i am still running into this issue. Right now on 2.4.0.
